<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\**" />
    <Content Remove="Entities\**" />
    <EmbeddedResource Remove="Entities\**" />
    <None Remove="Entities\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Models\RentalListViewModel.cs~RF119c872a.TMP" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Entities\Customer.cs" />
    <Compile Include="Entities\Employee.cs" />
    <Compile Include="Entities\Equipment.cs" />
    <Compile Include="Entities\GhostbustersFleetContext.cs" />
    <Compile Include="Entities\Maintenance.cs" />
    <Compile Include="Entities\Rental.cs" />
    <Compile Include="Entities\RentedEquipment.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
